---
# PHTN-30-000073
- name: Remove any existing "pam_faildelay" line
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_auth_file }}"
    regexp: "pam_faildelay"
    state: absent

- name: "PHTN-30-000073: The Photon operating system must enforce a delay of at least four seconds between logon prompts following a failed logon attempt."
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_auth_file }}"
    insertafter: EOF
    line: auth    optional    pam_faildelay.so delay=4000000
    state: present
