---
# PHTN-30-000100
- name: "PHTN-30-000100: The Photon operating system must prevent IPv4 Internet Control Message Protocol (ICMP) redirect messages from being accepted."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.accept_redirects
      value: "0"
    - name: net.ipv4.conf.default.accept_redirects
      value: "0"
    - name: net.ipv4.conf.eth0.accept_redirects
      value: "0"
