---
# PHTN-30-000070
- name: "PHTN-30-000070: The Photon operating system auditd service must generate audit records for all account creations, modifications, disabling, and termination events."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: -w /etc/security/opasswd -p wa -k opasswd
    state: present
  notify: load new audit rules
