---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^GSSAPIAuthentication "
    line: "GSSAPIAuthentication no"
    state: present
