---
# PHTN-30-000037
- name: "PHTN-30-000037: The Photon operating system must configure sshd to disconnect idle SSH sessions."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ClientAliveInterval "
    line: "ClientAliveInterval 900"
    state: present
