---
# PHTN-30-000024
- name: "PHTN-30-000024: The Photon operating system must require that new passwords are at least four characters different from the old password."
  community.general.pamd:
    name: system-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "difok=4"
    state: args_present
    backup: yes
