---
# PHTN-30-000067

# Note: The STIG Fix Text specifies the rules ending in '-F key=privileged'
# This is actually the result of the output from auditctl -l
# The rule needs to be loaded as '-k privileged'
# It will be converted to '-F' after the rules are loaded

# original: -a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -F key=privileged
# correct:  -a exit,always -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged

- name: "PHTN-30-000067: The Photon operating system must generate audit records when the sudo command is used."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    # STIG Fix Text defines -a always,exit
    # The /etc/audit/rules.d/audit.STIG.rules file already contains these lines but in -a exit,always
    # Either the existing lines have to be removed or the Fix Text needs to be corrected
    # /sbin/augenrules --load will produce an error due to rules already existing, otherwise
    line: -a exit,always -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged
    state: present
  notify: load new audit rules
