---
# PHTN-30-000078
- name: "PHTN-30-000078: The Photon operating system must configure sshd to disallow Generic Security Service Application Program Interface (GSSAPI) authentication."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^GSSAPIAuthentication "
    line: "GSSAPIAuthentication no"
    state: present
