---
# PHTN-30-000087
- name: "PHTN-30-000087: The Photon operating system must configure sshd to ignore user-specific known_host files."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^IgnoreUserKnownHosts "
    line: "IgnoreUserKnownHosts yes"
    state: present
