---
# PHTN-30-000099
- name: "PHTN-30-000099: The Photon operating system must not respond to IPv4 Internet Control Message Protocol (ICMP) echoes sent to a broadcast address."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.icmp_echo_ignore_broadcasts
      value: "1"
