---
# PHTN-30-000009
- name: "PHTN-30-000009: The Photon operating system must configure sshd to use approved encryption algorithms."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^FipsMode "
    line: "FipsMode yes"
    insertbefore: "^Ciphers "
    state: present
