---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^IgnoreUserKnownHosts "
    line: "IgnoreUserKnownHosts yes"
    state: present