---
# PHTN-30-000103
- name: "PHTN-30-000103: The Photon operating system must log IPv4 packets with impossible addresses."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.log_martians
      value: "1"
    - name: net.ipv4.conf.default.log_martians
      value: "1"
    - name: net.ipv4.conf.eth0.log_martians
      value: "1"
