---
# PHTN-30-000029
# The STIG Check and Fix mention 'password requisite pam_pwhistory.so' but the file by default only includes 'password required pam_pwhistory.so'.
# There is no mention to remove this line in the STIG, so this task will NOT remove that duplicate line.
# This results in PAM stacking...sort of...since the same module is being called out on both lines rather than just the control.
- name: "PHTN-30-000029: The Photon operating system must prohibit password reuse for a minimum of five generations."
  community.general.pamd:
    name: system-password
    new_type: password
    new_control: requisite
    new_module_path: pam_pwhistory.so
    module_arguments: "
      enforce_for_root
      use_authtok
      remember=5"
    state: after
    type: password
    control: requisite
    module_path: pam_cracklib.so
    backup: yes
