---
# PHTN-30-000044
- name: "PHTN-30-000044: The Photon operating system must audit all account disabling actions."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: -w /usr/bin/passwd -p x -k passwd
    state: present
  notify: load new audit rules
