---
# PHTN-30-000119
- name: "PHTN-30-000119: The Photon operating system must configure sshd to restrict AllowTcpForwarding."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^AllowTcpForwarding "
    line: "AllowTcpForwarding no"
    state: present
