---
# PHTN-30-000053
- name: "PHTN-30-000053: The Photon operating system must configure sshd with a specific ListenAddress."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ListenAddress "
    line: "ListenAddress {{ ansible_facts['eth0']['ipv4']['address'] }}"
    state: present
