---
# PHTN-30-000073
- name: "PHTN-30-000073: The Photon operating system must enforce a delay of at least four seconds between logon prompts following a failed logon attempt."
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_auth_file }}"
    regexp: ^auth.*optional.*pam_faildelay\.so.*
    line: auth optional pam_faildelay.so delay=4000000
    insertafter: EOF
    state: present

- name: "PHTN-30-000073: The Photon operating system must enforce a delay of at least four seconds between logon prompts following a failed logon attempt."
  community.general.pamd:
    name: system-auth
    type: auth
    control: optional
    module_path: pam_faildelay.so
    module_arguments: "delay=4000000"
    state: args_present
