---
# PHTN-30-000025
- name: "PHTN-30-000025: The Photon operating system must store only encrypted representations of passwords."
  ansible.builtin.lineinfile:
    path: "{{ var_login_defs_file }}"
    regexp: "ENCRYPT_METHOD "
    line: "ENCRYPT_METHOD SHA512"
    state: present
    backup: yes
