---
# PHTN-30-000043
- name: "PHTN-30-000043: The Photon operating system must audit all account modifications."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - line: -w /etc/passwd -p wa -k passwd
    - line: -w /etc/shadow -p wa -k shadow
    - line: -w /etc/group -p wa -k group
    - line: -w /etc/gshadow -p wa -k gshadow
  notify: load new audit rules
