---
# PHTN-30-000036
- name: "PHTN-30-000036: The Photon operating system must use TCP syncookies."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.tcp_syncookies
      value: "1"
