---
# PHTN-30-000014
- name: "PHTN-30-000014: The Photon operating system audit log must log space limit problems to syslog."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^space_left_action "
    line: "space_left_action = SYSLOG"
    state: present
