---
- name: The Photon operating system must be configured so that all global initialization scripts are protected from unathorized modification.
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "o-w"
  with_items:
    - path: "{{ var_bash_bashrc_file }}"
    - path: "{{ var_etc_profile_file }}"

- name: The Photon operating system must be configured so that all global initialization scripts are protected from unathorized modification.
  ansible.builtin.file:
    path: "{{ var_profile_d_directory }}"
    owner: root
    group: root
    mode: "o-w"
    recurse: yes
