---
# PHTN-30-000068
- name: "PHTN-30-000068: The Photon operating system must generate audit records when successful/unsuccessful logon attempts occur.."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - line: -w /var/log/faillog -p wa
    - line: -w /var/log/lastlog -p wa
    - line: -w /var/log/tallylog -p wa
  notify: load new audit rules
