---
# PHTN-30-000069
- name: "PHTN-30-000069: The Photon operating system must audit the insmod module."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: -w /sbin/insmod -p x
    state: present
  notify: load new audit rules
