---
# PHTN-30-000028
- name: "PHTN-30-000028: The Photon operating system must be configured so that passwords for new users are restricted to a 90-day maximum lifetime."
  ansible.builtin.lineinfile:
    path: "{{ var_login_defs_file }}"
    regexp: "^PASS_MAX_DAYS "
    line: "PASS_MAX_DAYS 90"
    state: present
    backup: yes
