---
# PHTN-30-000001
- name: "PHTN-30-000001: The Photon operating system must audit all account creations"
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - line: -w /usr/sbin/useradd -p x -k useradd
    - line: -w /usr/sbin/groupadd -p x -k groupadd
  notify: load new audit rules
