---
# PHTN-30-000114
- name: "PHTN-30-000114: The Photon operating system must set the UMASK parameter correctly."
  ansible.builtin.lineinfile:
    path: "{{ var_login_defs_file }}"
    regexp: "UMASK"
    line: "UMASK 077"
    state: present
    backup: yes
