---
# PHTN-30-000088
- name: "PHTN-30-000088: The Photon operating system must configure sshd to limit the number of allowed login attempts per connection."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^MaxAuthTries "
    line: "MaxAuthTries 6"
    state: present
