---
# PHTN-30-000102
- name: "PHTN-30-000102: The Photon operating system must not send IPv4 Internet Control Message Protocol (ICMP) redirects."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.send_redirects
      value: "0"
    - name: net.ipv4.conf.default.send_redirects
      value: "0"
    - name: net.ipv4.conf.eth0.send_redirects
      value: "0"
