---
# PHTN-30-000082
- name: "PHTN-30-000082: The Photon operating system must configure sshd to disallow Kerberos authentication."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^KerberosAuthentication "
    line: "KerberosAuthentication no"
    state: present
