---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^HostbasedAuthentication "
    line: "HostbasedAuthentication no"
    state: present
