---
# PHTN-30-000111
- name: Get a list of files.
  ansible.builtin.find:
    path: /boot/
    patterns: "*.cfg"
    use_regex: no
    file_type: file
  register: boot_cfg_files

# - debug: var=boot_cfg_files

- name: "PHTN-30-000111: The Photon operating system must protect all boot configuration files from unauthorized access."
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ boot_cfg_files.files }}"
