---
# PHTN-30-000120
- name: "PHTN-30-000120: The Photon operating system must configure sshd to restrict LoginGraceTime."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^LoginGraceTime "
    line: "LoginGraceTime 30"
    state: present
