---
# PHTN-30-000057
- name: The Photon operating system must configure auditd to log space limit problems to syslog.
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^space_left "
    line: "space_left = 75"
