---
# PHTN-30-000086
- name: "PHTN-30-000086: The Photon operating system must configure sshd to ignore user-specific trusted hosts lists."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^IgnoreRhosts "
    line: "IgnoreRhosts yes"
    state: present
