---
# PHTN-30-000003
- name: "PHTN-30-000003: The Photon operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting SSH access."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^Banner "
    line: "Banner /etc/issue"
    state: present

- name: "Copy the Standard Mandatory DoD Notice and Consent Banner to {{ var_etc_issue_file }}."
  ansible.builtin.copy:
    src: files/standard_mandatory_dod_notice_and_consent_banner.txt
    dest: "{{ var_etc_issue_file }}"
    owner: root
    group: root
    mode: "0644"
    backup: yes
