---
# PHTN-30-000092
- name: Get a list of file.
  ansible.builtin.find:
    path: "{{ var_profile_d_directory }}"
  register: profile_d_files

- name: "PHTN-30-000092: The Photon operating system must be configured so that all global initialization scripts are protected from unauthorized modification."
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "o-w"
  with_items:
    - path: "{{ var_bash_bashrc_file }}"
    - path: "{{ var_etc_profile_file }}"

- name: "PHTN-30-000092: The Photon operating system must be configured so that all global initialization scripts are protected from unauthorized modification."
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "o-w"
  loop: "{{ profile_d_files.files }}"
