---
# PHTN-30-000099
- name: Set kernel tunables using sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.icmp_echo_ignore_broadcasts
      value: "1"