---
# PHTN-30-000061
- name: "PHTN-30-000061: The Photon operating system RPM package management tool must cryptographically verify the authenticity of all software packages during installation."
  ansible.builtin.lineinfile:
    path: "{{ item.path }}"
    regexp: "^gpgcheck "
    line: "gpgcheck=1"
    state: present
    backup: yes
  with_items:
    - path: "{{ var_yum_repos_photon_debuginfo_repo_file }}"
    - path: "{{ var_yum_repos_photon_extras_repo_file }}"
    - path: "{{ var_yum_repos_photon_iso_repo_file }}"
    - path: "{{ var_yum_repos_photon_repo_file }}"
    - path: "{{ var_yum_repos_photon_updates_repo_file }}"
