---
# PHTN-30-000066
- name: The Photon operating system must remove ll software components after updated versions have been installed.
  ansible.builtin.lineinfile:
    path: "{{ var_tdnf_conf_file }}"
    regexp: "^clean_requirements_on_remove "
    line: "clean_requirements_on_remove=true"
    state: present
    backup: yes
