---
- name: The Photon operating system must be configured so that all system startup scripts are protected from unauthorized modification.
  ansible.builtin.file:
    path: "{{ var_etc_rc_d_directory }}"
    owner: root
    group: root
    mode: "o-w"
    recurse: yes
