---
# PHTN-30-000074
- name: "PHTN-30-000074: The Photon operating system must ensure audit events are flushed to disk at proper intervals."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^freq "
      line: "freq = 50"
    - regexp: "^flush "
      line: "flush = INCREMENTAL_ASYNC"
