---
# PHTN-30-000085
- name: "PHTN-30-000085: The Photon operating system must configure sshd to display the last login immediately after authentication."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^PrintLastLog "
    line: "PrintLastLog yes"
    state: present
