---
# PHTN-30-000107
- name: Set kernel tunables using sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.tcp_timestamps
      value: "1"