---
# PHTN-30-000011
- name: "PHTN-30-000011: The Photon operating system must configure auditd to use the correct log format."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^log_format "
    line: "log_format = raw"
    state: present
