---
# PHTN-30-000027
- name: "PHTN-30-000027: The Photon operating system must be configured so that passwords for new users are restricted to a 24-hour minimum lifetime."
  ansible.builtin.lineinfile:
    path: "{{ var_login_defs_file }}"
    regexp: "^PASS_MIN_DAYS "
    line: "PASS_MIN_DAYS 1"
    state: present
    backup: yes
