---
# PHTN-30-000098
- name: Set kernel tunables using sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.accept_source_route
      value: "0"
    - name: net.ipv4.conf.default.accept_source_route
      value: "0"
    - name: net.ipv4.conf.eth0.accept_source_route
      value: "0"
    - name: net.ipv6.conf.all.accept_source_route
      value: "0"
    - name: net.ipv6.conf.default.accept_source_route
      value: "0"
    - name: net.ipv6.conf.eth0.accept_source_route
      value: "0"