---
# PHTN-30-000071
- name: The Photon operating system must use the pam_cracklib module.
  community.general.pamd:
    name: system-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "
      dcredit=-1
      ucredit=-1
      lcredit=-1
      ocredit=-1
      minlen=8
      minclass=4
      difok=4
      retry=3
      maxsequence=0
      enforce_for_root"
    state: args_present
    backup: yes
