---
# PHTN-30-000103
- name: Set kernel tunables using sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.log_martians
      value: "1"
    - name: net.ipv4.conf.default.log_martians
      value: "1"
    - name: net.ipv4.conf.eth0.log_martians
      value: "1"