---
# PHTN-30-000110
- name: "PHTN-30-000110: The Photon operating system must enforce password complexity on the root account."
  community.general.pamd:
    name: system-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "enforce_for_root"
    state: args_present
    backup: yes
