---
# PHTN-30-000117
- name: "PHTN-30-000117: The Photon operating system must store only encrypted representations of passwords."
  community.general.pamd:
    name: system-password
    type: password
    control: required
    module_path: pam_unix.so
    module_arguments: "
      sha512
      shadow
      try_first_pass"
    state: args_present
    backup: yes
