---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ClientAliveCountMax "
    line: "ClientAliveCountMax 0"
    state: present
