---
# PHTN-30-000023
- name: "PHTN-30-000023: The Photon operating system must enforce password complexity by requiring that at least one numeric character be used."
  community.general.pamd:
    name: system-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "dcredit=-1"
    state: args_present
    backup: yes
