---
# PHTN-30-000015
- name: "PHTN-30-000015: The Photon operating system audit log must attempt to log audit failures to syslog."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^disk_full_action "
      line: "disk_full_action = SYSLOG"
    - regexp: "^disk_error_action "
      line: "disk_error_action = SYSLOG"
    - regexp: "^admin_space_left_action "
      line: "admin_space_left_action = SYSLOG"