---
# PHTN-30-000064
- name: "PHTN-30-000064: The Photon operating system must configure sshd to use FIPS 140-2 ciphers."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^Ciphers "
    line: "Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    state: present
