---
# PHTN-30-000005
- name: "PHTN-30-000005: The Photon operating system must set a session inactivity timeout of 15 minutes or less."
  ansible.builtin.lineinfile:
    path: "{{ var_tmout_sh_file }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  with_items:
    - line: TMOUT=900
    - line: readonly TMOUT
    - line: export TMOUT
    - line: mesg n 2>/dev/null
