---
# PHTN-30-000101
- name: "PHTN-30-000101: The Photon operating system must prevent IPv4 Internet Control Message Protocol (ICMP) secure redirect messages from being accepted."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.secure_redirects
      value: "0"
    - name: net.ipv4.conf.default.secure_redirects
      value: "0"
    - name: net.ipv4.conf.eth0.secure_redirects
      value: "0"
