---
# PHTN-30-000104
- name: Set kernel tunables using sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.rp_filter
      value: "1"
    - name: net.ipv4.conf.default.rp_filter
      value: "1"
    - name: net.ipv4.conf.eth0.rp_filter
      value: "1"