---
# PHTN-30-000105
- name: "PHTN-30-000105: The Photon operating system must not perform multicast packet forwarding."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.conf.all.mc_forwarding
      value: "0"
    - name: net.ipv4.conf.default.mc_forwarding
      value: "0"
    - name: net.ipv4.conf.eth0.mc_forwarding
      value: "0"
    - name: net.ipv6.conf.all.mc_forwarding
      value: "0"
    - name: net.ipv6.conf.default.mc_forwarding = 0net.ipv6.conf.eth0.mc_forwarding
      value: "0"
    - name: net.ipv6.conf.eth0.mc_forwarding
      value: "0"
