---
# PHTN-30-000107
- name: "PHTN-30-000107: The Photon operating system must send TCP timestamps."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.tcp_timestamps
      value: "1"
