# PHTN-30-000035
- name: The Photon operating system must disable new accounts immediately upon password expiration.
  ansible.builtin.lineinfile:
    path: "{{ var_useradd_file }}"
    line: INACTIVE=0
    state: present
    backup: yes