---
# PHTN-30-000042
- name: "PHTN-30-000042: The Photon operating system must audit all account modifications."
  ansible.builtin.lineinfile:
    path: "{{ var_audit_stig_rules_file }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - line: -w /usr/sbin/usermod -p x -k usermod
    - line: -w /usr/sbin/groupmod -p x -k groupmod
  notify: load new audit rules
