---
# PHTN-30-000115
- name: "PHTN-30-000115: The Photon operating system must configure sshd to disallow HostbasedAuthentication."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^HostbasedAuthentication "
    line: "HostbasedAuthentication no"
    state: present
