---
# PHTN-30-000030
- name: "PHTN-30-000030: The Photon operating system must enforce a minimum eight-character password length."
  community.general.pamd:
    name: system-password
    type: password
    control: requisite
    module_path: pam_cracklib.so
    module_arguments: "minlen=8"
    state: args_present
    backup: yes
