---
# PHTN-30-000056
- name: "PHTN-30-000056: The Photon operating system must configure auditd to keep logging in the event max log file size is reached."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^max_log_file_action "
    line: max_log_file_action = IGNORE
    state: present
