---
# PHTN-30-000080
- name: "PHTN-30-000080: The Photon operating system must configure sshd to disable X11 forwarding."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^X11Forwarding "
    line: "X11Forwarding no"
    state: present
