---
# PHTN-30-000106
- name: "PHTN-30-000106: The Photon operating system must not perform IPv4 packet forwarding."
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.ip_forward
      value: "0"
