---
# PHTN-30-000079
- name: "PHTN-30-000079: The Photon operating system must configure sshd to disable environment processing."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^PermitUserEnvironment "
    line: "PermitUserEnvironment no"
    state: present
