---
# PHTN-30-000056
- name: The Photon operating system must ensure audit events are flushed to disk at proper intervals.
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^max_log_file_action "
    line: max_log_file_action = IGNORE
    state: present
