---
# PHTN-30-000119
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^AllowTcpForwarding "
    line: "AllowTcpForwarding no"
    state: present
