---
# PHTN-30-000008
- name: 'PHTN-30-000008: The Photon operating system must have the sshd LogLevel set to "INFO".'
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^LogLevel "
    line: "LogLevel INFO"
    state: present
