---
# PHTN-30-000038
- name: "PHTN-30-000038: The Photon operating system must configure sshd to disconnect idle SSH sessions."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ClientAliveCountMax "
    line: "ClientAliveCountMax 0"
    state: present
