---
# PHTN-30-000083
- name: "PHTN-30-000083: The Photon operating system must configure sshd to disallow authentication with an empty password."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^PermitEmptyPasswords "
    line: "PermitEmptyPasswords no"
    state: present
