---
# PHTN-30-000039
- name: "PHTN-30-000039: The Photon operating system must configure rsyslog to offload system logs to a central server."
  ansible.builtin.lineinfile:
    path: "{{ var_rsyslog_config_file }}"
    line: "*.* {{ var_syslog_server_protocol }}{{ var_syslog_server_fqdn }}:{{ var_syslog_server_port }};RSYSLOG_SyslogProtocol23Format"
    state: present
  notify: restart rsyslog service