---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ClientAliveInterval "
    line: "ClientAliveInterval 900"
    state: present
