---
# PHTN-30-000084
- name: "PHTN-30-000084: The Photon operating system must configure sshd to disallow compression of the encrypted session stream."
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^Compression "
    line: "Compression no"
    state: present
