---
# PHTN-30-000055
- name: "PHTN-30-000055: The Photon operating system must configure auditd to keep five rotated log files."
  ansible.builtin.lineinfile:
    path: "{{ var_auditd_conf_file }}"
    regexp: "^num_logs "
    line: num_logs = 5
    state: present
