---
- name: Update SSH Configuration File
  ansible.builtin.lineinfile:
    path: "{{ var_sshd_config_file }}"
    regexp: "^ListenAddress "
    line: "ListenAddress {{ ansible_facts['default_ipv4']['address'] }}"
    state: present