---
# PHTN-30-000003
- name: The Photon operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting SSH access.
  ansible.builtin.copy:
    src: files/standard_mandatory_dod_notice_and_consent_banner.txt
    dest: "{{ var_etc_issue_file }}"
    owner: root
    group: root
    mode: '0644'
    backup: yes