---
# PHTN-30-000021
# PHTN-30-000022
# PHTN-30-000023
# PHTN-30-000024
# PHTN-30-000050
# PHTN-30-000071
# PHTN-30-000110
- name: Enforce password complexity - remove existing pam_cracklib.so lines
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_password_file }}"
    regexp: "pam_cracklib.so"
    state: absent

- name: Enforce password complexity - add new line
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_password_file }}"
    line: password requisite pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root
    insertafter: "# Begin"
    state: present

- name: Must only store encrypted representations of passwords
  ansible.builtin.lineinfile:
    path: "{{ var_login_defs_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    # PHTN-30-000025
    - regexp: "^ENCRYPT_METHOD "
      line: ENCRYPT_METHOD SHA512
    # PHTN-30-000027
    - regexp: "^PASS_MIN_DAYS "
      line: PASS_MIN_DAYS   1
    # PHTN-30-000028
    - regexp: "^PASS_MAX_DAYS "
      line: PASS_MAX_DAYS   90
    # PHTN-30-000072
    - regexp: "^FAIL_DELAY "
      line: FAIL_DELAY  4
    # PHTN-30-000075
    - regexp: "^CREATE_HOME"
      line: CREATE_HOME     yes
    # PHTN-30-000114
    - regexp: "^UMASK"
      line: UMASK 077
