---
# PHTN-30-000029
- name: Prohibit password reuse for a minumum of five generations
  ansible.builtin.lineinfile:
    path: "{{ var_pam_system_password_file }}"
    insertafter: "password requisite pam_cracklib.so"
    line: password requisite pam_pwhistory.so enforce_for_root use_authtok remember=5 retry=3
    state: present
