---
# PHTN-30-000004
- name: Limit concurrent sessions to 10
  ansible.builtin.lineinfile:
    path: "{{ var_limits_conf_file }}"
    line: "*              hard    maxlogins      10"
    state: absent

- name: Limit concurrent sessions to 10
  ansible.builtin.lineinfile:
    path: "{{ var_limits_conf_file }}"
    line: "*              hard    maxlogins      10"
    insertbefore: "# End of file"
    state: present
