---
# PHTN-30-000108
- name: Protect the SSH public host key from modification
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - path: /etc/ssh/ssh_host_dsa_key.pub
    - path: /etc/ssh/ssh_host_ecdsa_key.pub
    - path: /etc/ssh/ssh_host_ed25519_key.pub
    - path: /etc/ssh/ssh_host_rsa_key.pub
