---
# PHTN-30-000005
- name: Set session inactivity timer of 15 minutes
  ansible.builtin.lineinfile:
    path: "{{ var_tmout_sh_file }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - line: TMOUT=900
    - line: readonly TMOUT
    - line: export TMOUT
    - line: mesg n 2>/dev/null
