---
- name: RPM package management tool must cryptographically verify the authenticity
  ansible.builtin.lineinfile:
    path: "{{ var_tdnf_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    # PHTN-30-000060
    - regexp: "^gpgcheck"
      line: gpgcheck=1
    # PHTN-30-000066
    - regexp: "^clean_requirements_on_remove"
      line: clean_requirements_on_remove=true