---
# PHTN-30-000007
- name: Check for sshd Authentication logging
  ansible.builtin.lineinfile:
    path: "{{ var_rsyslog_config_file }}"
    regexp: "^authpriv "
    line: "authpriv.*   /var/log/auth.log"
    state: present
    backup: yes
  notify: restart rsyslog service

# PHTN-30-000039
- name: Must configure rsyslog to offload system logs to a central server
  ansible.builtin.lineinfile:
    path: "{{ var_rsyslog_config_file }}"
    line: "*.* {{ var_syslog_server_protocol }}{{ var_syslog_server_fqdn }}:{{ var_syslog_server_port }};RSYSLOG_SyslogProtocol23Format"
    state: present
  notify: restart rsyslog service