---
- name: Replace the system-password file.
  ansible.builtin.copy:
    src: files/system_password
    dest: "{{ var_pam_system_password_file }}"
    owner: root
    group: root
    mode: '0600'
    backup: yes

# # PHTN-30-000021
# - name: The Photon operating system must enforce password complexity by requiring that at least one uppercase character be used.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000022
# - name: The Photon operating system must enforce password complexity by requiring that at least one lowercase character be used.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000023
# - name: The Photon operating system must enforce password complexity by requiring that at least one numeric character be used.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000024
# - name: The Photon operating system must require that the new passwords are at least four characters different from the old password.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000029
# - name: Prohibit password reuse for a minumum of five generations
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     insertafter: "password requisite pam_cracklib.so"
#     line: password requisite pam_pwhistory.so enforce_for_root use_authtok remember=5 retry=3
#     state: present

# # PHTN-30-000030
# - name: The Photon operating system must enforce a minimum eight-charater password length.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000050
# - name: The Photon operating system must enforce password complexity by requiring that at least one special character be used.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000071
# - name: The Photon operating system must use the pam_cracklib module.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "password    requisite "
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present

# # PHTN-30-000110
# - name: The Photon operating system must enforce password complexity on the root account.
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "pam_cracklib"
#     line: "password   requisite   pam_cracklib.so dcredit=-1 ucredit=-1 lcredit=-1 ocredit=-1 minlen=8 minclass=4 difok=4 retry=3 maxsequence=0 enforce_for_root"
#     state: present
#     backup: yes

# # PHTN-30-000117
# - name: Must store only encrypted representations of passwords
#   ansible.builtin.lineinfile:
#     path: "{{ var_pam_system_password_file }}"
#     regexp: "sha512"
#     line: password required pam_unix.so sha512 shadow try_first_pass
#     state: present